import unittest


class HashTableTestCase(unittest.TestCase):
    def test___getitem__(self): ...
    def test___setitem__(self): ...
    def test___delitem__(self): ...
    def test___iter__(self): ...
    def test___eq__(self): ...
    def test___contains__(self): ...
    def test___len__(self): ...
    def test_keys(self): ...
    def test_values(self): ...
    def test_items(self): ...
    def test_update(self): ...
    def test_setdefault(self): ...
    def test_get(self): ...
    def test_pop(self): ...
    def test_popitem(self): ...
    def test_clear(self): ...


class HashFunctionTestCase(unittest.TestCase):
    def test_hash_function(self): ...
