from collections.abc import MutableMapping
from typing import Iterator, TypeVar, Union

KT = TypeVar('KT')
VT = TypeVar('VT')


def hash_function(obj: Union[str, int]) -> int: ...


class HashTable(MutableMapping[KT, VT]):
    def __init__(self, capacity: int) -> None: ...
    def __getitem__(self, key: KT, /) -> VT: ...
    def __setitem__(self, key: KT, value: VT, /) -> None: ...
    def __delitem__(self, key: KT, /) -> None: ...
    def __iter__(self) -> Iterator[KT]: ...
    def __len__(self) -> int: ...
